version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '8000:8000'
    depends_on:
      - backend

  backend:
    build: ./
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'mysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}'
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
